version: 2

workflows:
  version: 2
  default:
    jobs:
      - primary:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
# ------------------------------------------------------------------------------
 jobs:
        primary:
          docker:
            - image: mbgl/feb0443038:android-27-alpha
          working_directory: ~/code
          environment:
            JVM_OPTS: -Xmx3200m
            BUILDTYPE: Debug
            IS_LOCAL_DEVELOPMENT: false
          steps:
            - checkout
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Clean gradle
                command: ./gradlew clean
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                paths:
                  - ~/.gradle
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Log in to Google Cloud Platform
                shell: /bin/bash -euo pipefail
                command: |
                  echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
                  gcloud auth activate-service-account --key-file secret.json --project mapbox-android-demo
                  rm secret.json
            - run:
                name: Check code style
                command: make checkstyle
            - run:
                name: Run Firebase instrumentation tests
                command: |
                  #!/bin/bash
                  echo "Build seperate test apk:"
                  ./gradlew :MapboxAndroidDemo:assembleGpservicesDebug --continue
                  gcloud firebase test android run --type robo --app app/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk --device-ids shamu --os-version-ids 22 --locales en --orientations portrait --timeout 5m
            - store_artifacts:
                path: app/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk
      # ------------------------------------------------------------------------------